import 'branch.dart';

const List<Branch> branches = [
  Branch(
    id: "b1",
    name: "فرع المشاية",
    city: "جدة",
    address: "حي البلد التاريخي، شارع المشاية",
    hours: "٧ص - ١٢م",
    phone: "+966 12 XXX XXXX",
    isOpen: true,
    waitTime: "٥ دقائق",
    x: 25,
    y: 60,
  ),
  Branch(
    id: "b2",
    name: "فرع العليا",
    city: "الرياض",
    address: "حي العليا، طريق الملك فهد",
    hours: "٦ص - ١م",
    phone: "+966 11 XXX XXXX",
    isOpen: true,
    waitTime: "١٠ دقائق",
    x: 55,
    y: 42,
  ),
  Branch(
    id: "b3",
    name: "فرع الخبر",
    city: "الخبر",
    address: "حي الثقبة، كورنيش الخبر",
    hours: "٧ص - ١٢م",
    phone: "+966 13 XXX XXXX",
    isOpen: false,
    waitTime: "مغلق",
    x: 72,
    y: 38,
  ),
  Branch(
    id: "b4",
    name: "فرع مكة المكرمة",
    city: "مكة",
    address: "العزيزية، بالقرب من الحرم",
    hours: "٢٤ ساعة",
    phone: "+966 12 XXX XXXX",
    isOpen: true,
    waitTime: "٧ دقائق",
    x: 35,
    y: 52,
  ),
];
