import 'product.dart';

const List<Product> products = [
  Product(
    id: "arabic-1",
    name: "قهوة سعودية بالهيل",
    nameEn: "Saudi Cardamom Coffee",
    category: "arabic",
    price: 15,
    image: "https://images.unsplash.com/photo-1769781383545-6b60e30eb88c?w=600&q=80",
    description: "قهوة عربية أصيلة محضّرة بأجود حبوب البن مع الهيل والزعفران",
    sensory: "كثيفة كالديجور الصباحي... عطرها يسبق طعمها",
    tags: ["تقليدي", "بدون سكر"],
    isFeatured: true,
    calories: 15,
    sizes: [
      ProductSize(label: "صغير", price: 15),
      ProductSize(label: "وسط", price: 18),
      ProductSize(label: "كبير", price: 22),
    ],
  ),
  Product(
    id: "arabic-2",
    name: "قهوة الزعفران الملكية",
    nameEn: "Royal Saffron Coffee",
    category: "arabic",
    price: 25,
    image: "https://images.unsplash.com/photo-1747775650474-8dd9cf82cb6c?w=600&q=80",
    description: "مزيج نادر من القهوة العربية مع خيوط الزعفران الإيراني الأصيل",
    sensory: "ذهبية اللون... دافئة كأشعة الشمس في الضحى",
    tags: ["فاخر", "محدود"],
    isNew: true,
    isFeatured: true,
    calories: 20,
    sizes: [
      ProductSize(label: "صغير", price: 25),
      ProductSize(label: "كبير", price: 30),
    ],
  ),
  Product(
    id: "espresso-1",
    name: "إسبريسو ربل",
    nameEn: "Double Espresso",
    category: "espresso",
    price: 12,
    image: "https://images.unsplash.com/photo-1613158556069-e7d8eae76214?w=600&q=80",
    description: "جرعة مضاعفة من أجود حبوب الأرابيكا المحمّصة على الطريقة الإيطالية",
    sensory: "قوي كالإرادة... حاد كالحقيقة",
    tags: ["قوي", "كلاسيكي"],
    isFeatured: true,
    calories: 5,
    sizes: [
      ProductSize(label: "ربل", price: 12),
      ProductSize(label: "ثلاثي", price: 16),
    ],
  ),
  Product(
    id: "espresso-2",
    name: "كابتشينو بن الغالي",
    nameEn: "Al-Ghali Cappuccino",
    category: "espresso",
    price: 20,
    image: "https://images.unsplash.com/photo-1649780567041-344d8f485e74?w=600&q=80",
    description: "كابتشينو مرسوم بالفن مع حليب الأبقار الطازج والإسبريسو المحضّر بعناية",
    sensory: "ناعم كالحرير... دافئ كالعناق الأول",
    tags: ["لاتيه آرت", "حليب"],
    isFeatured: true,
    calories: 120,
    sizes: [
      ProductSize(label: "صغير", price: 18),
      ProductSize(label: "وسط", price: 20),
      ProductSize(label: "كبير", price: 23),
    ],
  ),
  Product(
    id: "espresso-3",
    name: "لاتيه المعتّق",
    nameEn: "Aged Latte",
    category: "espresso",
    price: 22,
    image: "https://images.unsplash.com/photo-1762657440624-d0b5cfae5bac?w=600&q=80",
    description: "إسبريسو مع حليب مبخّر وإضافة سرّية من البن المعتّق لمدة ٣٠ يوماً",
    sensory: "عميق كالذكريات... يتحسّن مع كل رشفة",
    tags: ["حصري", "فاخر"],
    isNew: true,
    calories: 150,
    sizes: [
      ProductSize(label: "وسط", price: 22),
      ProductSize(label: "كبير", price: 26),
    ],
  ),
  Product(
    id: "espresso-4",
    name: "أمريكانو أصيل",
    nameEn: "Authentic Americano",
    category: "espresso",
    price: 14,
    image: "https://images.unsplash.com/photo-1736813133035-6baf4762fd3d?w=600&q=80",
    description: "إسبريسو مخفّف بالماء الساخن... بسيط في شكله، عميق في جوهره",
    sensory: "صافٍ كالنية... صادق كالبداية",
    tags: ["خفيف", "كلاسيكي"],
    calories: 10,
    sizes: [
      ProductSize(label: "صغير", price: 12),
      ProductSize(label: "وسط", price: 14),
      ProductSize(label: "كبير", price: 16),
    ],
  ),
  Product(
    id: "cold-1",
    name: "كولد برو الليلي",
    nameEn: "Night Cold Brew",
    category: "cold",
    price: 22,
    image: "https://images.unsplash.com/photo-1777993623617-abc6adebea40?w=600&q=80",
    description: "قهوة منقوعة باردة لـ ٢٤ ساعة في الظلام، تُقدّم مع مكعبات الجليد الفاخرة",
    sensory: "غامض كالليل... حلو كالأسرار المدفونة",
    tags: ["بارد", "منقوع"],
    isFeatured: true,
    calories: 25,
    sizes: [
      ProductSize(label: "وسط", price: 22),
      ProductSize(label: "كبير", price: 26),
    ],
  ),
  Product(
    id: "cold-2",
    name: "قهوة التمر المثلجة",
    nameEn: "Iced Date Coffee",
    category: "cold",
    price: 25,
    image: "https://images.unsplash.com/photo-1630620276854-c68ae3b47678?w=600&q=80",
    description: "مزيج سعودي فريد من القهوة الباردة مع شراب التمر المجدول الطبيعي",
    sensory: "حلو بطريقة الجنوب... دافئ المذاق رغم برودته",
    tags: ["سعودي", "تمر"],
    isNew: true,
    isFeatured: true,
    calories: 180,
    sizes: [
      ProductSize(label: "وسط", price: 25),
      ProductSize(label: "كبير", price: 29),
    ],
  ),
  Product(
    id: "cold-3",
    name: "فرابيه الغالي",
    nameEn: "Al-Ghali Frappe",
    category: "cold",
    price: 28,
    image: "https://images.unsplash.com/photo-1773106287475-6a7c1b3e1e13?w=600&q=80",
    description: "مزيج متجمّد من الإسبريسو والكريمة والشوكولاتة البيضاء الفاخرة",
    sensory: "منعش كالنسيم... فاخر كالرفاهية المستحقة",
    tags: ["بارد", "حلو"],
    calories: 320,
    sizes: [
      ProductSize(label: "وسط", price: 28),
      ProductSize(label: "كبير", price: 32),
    ],
  ),
  Product(
    id: "sweets-1",
    name: "كيكة القهوة العربية",
    nameEn: "Arabic Coffee Cake",
    category: "sweets",
    price: 22,
    image: "https://images.unsplash.com/photo-1736813133035-6baf4762fd3d?w=600&q=80",
    description: "كيكة مبللة بالقهوة العربية والهيل مع كريمة الزبدة والمكسرات",
    sensory: "طرية كالذكريات... عطرة كأمسيات الخميس",
    tags: ["حلو", "قهوة"],
    calories: 380,
  ),
  Product(
    id: "sweets-2",
    name: "تشيز كيك البن الغالي",
    nameEn: "Al-Ghali Coffee Cheesecake",
    category: "sweets",
    price: 28,
    image: "https://images.unsplash.com/photo-1649780567041-344d8f485e74?w=600&q=80",
    description: "تشيز كيك نيويورك الفاخر بطبقة الإسبريسو والكراميل المملّح",
    sensory: "كريمي كالحلم... مرّ حلو كالتناقض الجميل",
    tags: ["مخبوزات", "فاخر"],
    isNew: true,
    calories: 420,
  ),
];
